<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TR5ELL5" name="HW4.tests.CRUDUserTests" tests="5" failures="0" timestamp="16 Dec 2016 09:59:38 GMT" time="41.324" errors="1">
  <testcase name="positiveUpdateTest" time="9.165" classname="HW4.tests.CRUDUserTests"/>
  <testcase name="negativeInsertTest" time="6.043" classname="HW4.tests.CRUDUserTests"/>
  <testcase name="positiveDeleteTest" time="12.416" classname="HW4.tests.CRUDUserTests"/>
  <testcase name="positiveInsertTest" time="7.631" classname="HW4.tests.CRUDUserTests"/>
  <testcase name="positiveReadTest" time="6.069" classname="HW4.tests.CRUDUserTests">
    <error type="java.lang.AssertionError" message="The following asserts failed:
Wrong users don&#039;t equels">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong users don't equels
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at HW4.tests.CRUDUserTests.positiveReadTest(CRUDUserTests.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- positiveReadTest -->
</testsuite> <!-- HW4.tests.CRUDUserTests -->
